name: check with stdlib-1.7.3
on: [push]
jobs:
  check:
    name: Check ValiantRefinement.agda (the main file)
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wenkokke/setup-agda@v2.1.0
        with:
          agda-version: '2.6.3'
          agda-stdlib-version: '1.7.3'
      - working-directory: code
        run: agda ValiantRefinement.agda
