name: basic
on: [push]
jobs:
  check:
    name: Check ValiantRefinement.agda (the main file)
    runs-on: ubuntu-latest # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: wenkokke/setup-agda@v2
        with:
          agda-version: '2.6.4'
          agda-stdlib-version: '2.0'
      - working-directory: code
        run: agda ValiantRefinement.agda
